server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/taskdb
    username: task
    password: p@ssw0rd
    driver-class-name: org.postgresql.Driver


jpa:
    hibernate:
      ddl-auto: update
    show-sql: true