server:
  port: 8080

spring:
  # Database Configuration
  datasource:
    url: jdbc:postgresql://localhost:5432/taskdb
    username: task
    password: p@ssw0rd
    driver-class-name: org.postgresql.Driver

  # JPA Configuration
  jpa:
    hibernate:
      ddl-auto: create-drop #create-drop   pdate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format-sql: true
    show-sql: true

  # Security Configuration
  security:
    user:
      name: test
      password: test

  # Email Configuration
  mail:
    host: smtp.elasticemail.com
    port: 2525
    username: ebtisamalaama@gmail.com
    password: 2A5FF5C4131477E0A9B3DCBB4B223C0F0FB5
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
      from: test.test13390@outlook.com
      to: Ebtisamalaama@gmail.com        
      

       
  
  

# Logging Configuration
logging:
  level:
    "[org.springframework.security]": DEBUG
    "[org.springframework.mail]": DEBUG
